// <auto-generated />
using System;
using EventiApplication.WebAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EventiApplication.WebAPI.Migrations
{
    [DbContext(typeof(MojContext))]
    [Migration("20200704112352_Prva")]
    partial class Prva
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EventiApplication.WebAPI.Database.Administrator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GradId")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uloga")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GradId");

                    b.ToTable("Administrator");
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.Drzava", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Drzava");
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdministratorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumOdrzavanja")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOdobren")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOtkazan")
                        .HasColumnType("bit");

                    b.Property<int?>("KategorijaId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizatorId")
                        .HasColumnType("int");

                    b.Property<int>("ProstorOdrzavanjaId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Slika")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("SlikaThumb")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("VrijemeOdrzavanja")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdministratorId");

                    b.HasIndex("KategorijaId");

                    b.HasIndex("OrganizatorId");

                    b.HasIndex("ProstorOdrzavanjaId");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.Grad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DrzavaId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DrzavaId");

                    b.ToTable("Grad");
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.Karta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Cijena")
                        .HasColumnType("real");

                    b.Property<DateTime>("DatumKupovine")
                        .HasColumnType("datetime2");

                    b.Property<int>("KupovinaTipId")
                        .HasColumnType("int");

                    b.Property<byte[]>("QrCode")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("TipKarteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KupovinaTipId");

                    b.HasIndex("TipKarteId");

                    b.ToTable("Karta");
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.Kategorija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kategorija");
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GradId")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAktivan")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostanskiBroj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Slika")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("SlikaThumb")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uloga")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GradId");

                    b.ToTable("Korisnik");
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.Kupovina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Kupovina");
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.KupovinaTip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojKarata")
                        .HasColumnType("int");

                    b.Property<float>("Cijena")
                        .HasColumnType("real");

                    b.Property<int>("KupovinaId")
                        .HasColumnType("int");

                    b.Property<int?>("ProdajaTipId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KupovinaId");

                    b.HasIndex("ProdajaTipId");

                    b.ToTable("KupovinaTip");
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumLajka")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Like");
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.Ocjena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("OcjenaEventa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Ocjena");
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.Organizator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GradId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uloga")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GradId");

                    b.ToTable("Organizator");
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.PozivNaEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOdbijen")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrihvacen")
                        .HasColumnType("bit");

                    b.Property<int>("KorisnikPozivalacId")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikPozvaniId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("KorisnikPozivalacId");

                    b.HasIndex("KorisnikPozvaniId");

                    b.ToTable("PozivNaEvent");
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.Prijateljstvo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumSlanjaZahtjeva")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPrihvaceno")
                        .HasColumnType("bit");

                    b.Property<int>("KorisnikPosiljalacId")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikPrimalacId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikPosiljalacId");

                    b.HasIndex("KorisnikPrimalacId");

                    b.ToTable("Prijateljstvo");
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.ProdajaTip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojProdatihKarataTip")
                        .HasColumnType("int");

                    b.Property<float>("CijenaTip")
                        .HasColumnType("real");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<bool>("PostojeSjedista")
                        .HasColumnType("bit");

                    b.Property<int?>("TipKarteId")
                        .HasColumnType("int");

                    b.Property<int>("UkupnoKarataTip")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("TipKarteId");

                    b.ToTable("ProdajaTip");
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.ProstorOdrzavanja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GradId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TipProstoraOdrzavanjaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GradId");

                    b.HasIndex("TipProstoraOdrzavanjaId");

                    b.ToTable("ProstorOdrzavanja");
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.Recenzija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Komentar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KupovinaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KupovinaId");

                    b.ToTable("Recenzija");
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.Sjediste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojSjedista")
                        .HasColumnType("int");

                    b.Property<int>("KartaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KartaId");

                    b.ToTable("Sjediste");
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.TipKarte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipKarte");
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.TipProstoraOdrzavanja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipProstoraOdrzavanja");
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.Administrator", b =>
                {
                    b.HasOne("EventiApplication.WebAPI.Database.Grad", "Grad")
                        .WithMany("Administrator")
                        .HasForeignKey("GradId");
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.Event", b =>
                {
                    b.HasOne("EventiApplication.WebAPI.Database.Administrator", "Administrator")
                        .WithMany("Event")
                        .HasForeignKey("AdministratorId");

                    b.HasOne("EventiApplication.WebAPI.Database.Kategorija", "Kategorija")
                        .WithMany()
                        .HasForeignKey("KategorijaId");

                    b.HasOne("EventiApplication.WebAPI.Database.Organizator", "Organizator")
                        .WithMany("Event")
                        .HasForeignKey("OrganizatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventiApplication.WebAPI.Database.ProstorOdrzavanja", "ProstorOdrzavanja")
                        .WithMany("Event")
                        .HasForeignKey("ProstorOdrzavanjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.Grad", b =>
                {
                    b.HasOne("EventiApplication.WebAPI.Database.Drzava", "Drzava")
                        .WithMany("Grad")
                        .HasForeignKey("DrzavaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.Karta", b =>
                {
                    b.HasOne("EventiApplication.WebAPI.Database.KupovinaTip", "KupovinaTip")
                        .WithMany("Karta")
                        .HasForeignKey("KupovinaTipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventiApplication.WebAPI.Database.TipKarte", "TipKarte")
                        .WithMany()
                        .HasForeignKey("TipKarteId");
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.Korisnik", b =>
                {
                    b.HasOne("EventiApplication.WebAPI.Database.Grad", "Grad")
                        .WithMany("Korisnik")
                        .HasForeignKey("GradId");
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.Kupovina", b =>
                {
                    b.HasOne("EventiApplication.WebAPI.Database.Event", "Event")
                        .WithMany("Kupovina")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventiApplication.WebAPI.Database.Korisnik", "Korisnik")
                        .WithMany("Kupovina")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.KupovinaTip", b =>
                {
                    b.HasOne("EventiApplication.WebAPI.Database.Kupovina", "Kupovina")
                        .WithMany("KupovinaTip")
                        .HasForeignKey("KupovinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventiApplication.WebAPI.Database.ProdajaTip", "ProdajaTip")
                        .WithMany("KupovinaTip")
                        .HasForeignKey("ProdajaTipId");
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.Like", b =>
                {
                    b.HasOne("EventiApplication.WebAPI.Database.Event", "Event")
                        .WithMany("Like")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventiApplication.WebAPI.Database.Korisnik", "Korisnik")
                        .WithMany("Like")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.Ocjena", b =>
                {
                    b.HasOne("EventiApplication.WebAPI.Database.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventiApplication.WebAPI.Database.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.Organizator", b =>
                {
                    b.HasOne("EventiApplication.WebAPI.Database.Grad", "Grad")
                        .WithMany("Organizator")
                        .HasForeignKey("GradId");
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.PozivNaEvent", b =>
                {
                    b.HasOne("EventiApplication.WebAPI.Database.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventiApplication.WebAPI.Database.Korisnik", "KorisnikPozivalac")
                        .WithMany("PozivNaEventKorisnikPozivalac")
                        .HasForeignKey("KorisnikPozivalacId")
                        .IsRequired();

                    b.HasOne("EventiApplication.WebAPI.Database.Korisnik", "KorisnikPozvani")
                        .WithMany("PozivNaEventKorisnikPozvani")
                        .HasForeignKey("KorisnikPozvaniId")
                        .IsRequired();
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.Prijateljstvo", b =>
                {
                    b.HasOne("EventiApplication.WebAPI.Database.Korisnik", "KorisnikPosiljalac")
                        .WithMany("PrijateljstvoKorisnikPosiljalac")
                        .HasForeignKey("KorisnikPosiljalacId")
                        .IsRequired();

                    b.HasOne("EventiApplication.WebAPI.Database.Korisnik", "KorisnikPrimalac")
                        .WithMany("PrijateljstvoKorisnikPrimalac")
                        .HasForeignKey("KorisnikPrimalacId")
                        .IsRequired();
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.ProdajaTip", b =>
                {
                    b.HasOne("EventiApplication.WebAPI.Database.Event", "Event")
                        .WithMany("ProdajaTip")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventiApplication.WebAPI.Database.TipKarte", "TipKarte")
                        .WithMany()
                        .HasForeignKey("TipKarteId");
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.ProstorOdrzavanja", b =>
                {
                    b.HasOne("EventiApplication.WebAPI.Database.Grad", "Grad")
                        .WithMany("ProstorOdrzavanja")
                        .HasForeignKey("GradId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventiApplication.WebAPI.Database.TipProstoraOdrzavanja", "TipProstoraOdrzavanja")
                        .WithMany()
                        .HasForeignKey("TipProstoraOdrzavanjaId");
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.Recenzija", b =>
                {
                    b.HasOne("EventiApplication.WebAPI.Database.Kupovina", "Kupovina")
                        .WithMany("Recenzija")
                        .HasForeignKey("KupovinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventiApplication.WebAPI.Database.Sjediste", b =>
                {
                    b.HasOne("EventiApplication.WebAPI.Database.Karta", "Karta")
                        .WithMany("Sjediste")
                        .HasForeignKey("KartaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
