//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventiApplication.WinUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EventiApplication.WinUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neispravni podaci poslani.
        /// </summary>
        internal static string BadRqst {
            get {
                return ResourceManager.GetString("BadRqst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemate pravo pristupa.
        /// </summary>
        internal static string Forrbiden {
            get {
                return ResourceManager.GetString("Forrbiden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greska na serveru.
        /// </summary>
        internal static string IntServerErr {
            get {
                return ResourceManager.GetString("IntServerErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne mozete obrisati ovaj event, postoje obavljene kupovine.
        /// </summary>
        internal static string nemBrisanjeEventa {
            get {
                return ResourceManager.GetString("nemBrisanjeEventa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne mozete obrisati ovog organizatora, posjeduje organizovane evente.
        /// </summary>
        internal static string nemBrisanjeOrg {
            get {
                return ResourceManager.GetString("nemBrisanjeOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne mozete obrisati ovu prodaju tipa karte.
        /// </summary>
        internal static string nemBrisanjeProdaje {
            get {
                return ResourceManager.GetString("nemBrisanjeProdaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne mozete obrisati ovaj prostor odrzavanja, postoje najavljeni eventi za ovaj prostor.
        /// </summary>
        internal static string nemBrisanjeProstoraOdr {
            get {
                return ResourceManager.GetString("nemBrisanjeProstoraOdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne mozete obrisati ovaj tip karte, jer postoje definisane prodaje.
        /// </summary>
        internal static string nemBrisanjeTipaKarte {
            get {
                return ResourceManager.GetString("nemBrisanjeTipaKarte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije promijenjen status aktivnosti.
        /// </summary>
        internal static string nijePromijenjenStatus {
            get {
                return ResourceManager.GetString("nijePromijenjenStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morate selektovati kompletan red eventa za koji zelite uraditi izabranu akciju..
        /// </summary>
        internal static string selectRedEventa {
            get {
                return ResourceManager.GetString("selectRedEventa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morate selektovati kompletan red korisnika za kojeg zelite uraditi izabranu akciju..
        /// </summary>
        internal static string selectRedKorisnika {
            get {
                return ResourceManager.GetString("selectRedKorisnika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morate selektovati kompletan red organizatora za kojeg zelite uraditi izabranu akciju..
        /// </summary>
        internal static string selectRedOrganizatora {
            get {
                return ResourceManager.GetString("selectRedOrganizatora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morate selektovati kompletan red prostora odrzavanja za koji zelite uraditi izabranu akciju..
        /// </summary>
        internal static string selectRedProstoraOdrzavanja {
            get {
                return ResourceManager.GetString("selectRedProstoraOdrzavanja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morate selektovati kompletan red tipa karte za koji zelite uraditi izabranu akciju..
        /// </summary>
        internal static string selectTipKarte {
            get {
                return ResourceManager.GetString("selectTipKarte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morate selektovati kompletan red tipa prodaje/karte za koji zelite uraditi izabranu akciju..
        /// </summary>
        internal static string selectTipProdaje {
            get {
                return ResourceManager.GetString("selectTipProdaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niste autentificirani, pogresno korisnicko ime ili lozinka.
        /// </summary>
        internal static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspjesno obavljena akcija.
        /// </summary>
        internal static string UspjesnaAkcija {
            get {
                return ResourceManager.GetString("UspjesnaAkcija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspjesno dodavanje eventa.
        /// </summary>
        internal static string UspjesnoDodavanjeEvent {
            get {
                return ResourceManager.GetString("UspjesnoDodavanjeEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspjesna izmjena eventa.
        /// </summary>
        internal static string UspjesnoIzmijenjenEvent {
            get {
                return ResourceManager.GetString("UspjesnoIzmijenjenEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U formatu text@nekiMail.com.
        /// </summary>
        internal static string valErrEmailFormat {
            get {
                return ResourceManager.GetString("valErrEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalno 2 karatktera, maksimalno 30.
        /// </summary>
        internal static string valErrMinLenght2 {
            get {
                return ResourceManager.GetString("valErrMinLenght2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalno 3 karaktera, maksimalno 40.
        /// </summary>
        internal static string valErrMinLenght3 {
            get {
                return ResourceManager.GetString("valErrMinLenght3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morate izabrati neku stavku.
        /// </summary>
        internal static string valErrObavezanIzbor {
            get {
                return ResourceManager.GetString("valErrObavezanIzbor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezan izbor slike.
        /// </summary>
        internal static string valErrObaveznaSlika {
            get {
                return ResourceManager.GetString("valErrObaveznaSlika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdite uneseni password.
        /// </summary>
        internal static string valErrPassConfirmation {
            get {
                return ResourceManager.GetString("valErrPassConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalno 8 karaktera, maksimalno 50.
        /// </summary>
        internal static string valErrPassword1 {
            get {
                return ResourceManager.GetString("valErrPassword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebna kombinacija velikih i malih slova i brojeva.
        /// </summary>
        internal static string valErrPassword2 {
            get {
                return ResourceManager.GetString("valErrPassword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno polje.
        /// </summary>
        internal static string valErrRequired {
            get {
                return ResourceManager.GetString("valErrRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morate unijeti samo brojeve.
        /// </summary>
        internal static string valErrSamoBrojevi {
            get {
                return ResourceManager.GetString("valErrSamoBrojevi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U formatu 000111222.
        /// </summary>
        internal static string valErrTelefonFormat {
            get {
                return ResourceManager.GetString("valErrTelefonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U formatu aa:bb.
        /// </summary>
        internal static string valErrTimeMatching {
            get {
                return ResourceManager.GetString("valErrTimeMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrijednost mora biti veca od nula.
        /// </summary>
        internal static string valErrVeceOd0 {
            get {
                return ResourceManager.GetString("valErrVeceOd0", resourceCulture);
            }
        }
    }
}
